### PR TITLE
Adds Contributing Document

### PR DESCRIPTION
**Pull request by ncronquist**
Signed-off-by: Nick Cronquist <nick.cronquist@sap.com>

### CODE REVIEW

**Review by nicklathe — DISMISSED** [review]
:shipit:

**Review by dragan — DISMISSED** [review]
LGTM :shipit:

**Comment by ncronquist** [comment]
@dragan @nicklathe Rebased this PR after merging the license PR #1

**Review by dragan — APPROVED** [review]
:shipit:

**Pull request merged**
