### PR TITLE
Adds Issue Templates

### PR DESCRIPTION
**Pull request by ncronquist**
- Adds issue templates for:
  - bug reports
  - feature requests
  - support requests

### CODE REVIEW

**Review by nicklathe — DISMISSED** [review]
LGTM :shipit:

**Review by dragan — DISMISSED** [review]
LGTM :shipit:

**Comment by ncronquist** [comment]
@dragan @nicklathe Rebased on latest master changes.

**Review by dragan — APPROVED** [review]
:shipit:

**Pull request merged**
