### PR TITLE
License under Apache 2.0

### PR DESCRIPTION
**Pull request by ncronquist**
- Since we're not doing these repos together, I figured I would start by creating pull requests
  - Let me know if you would prefer that the base repository setup (license, readme, issues, etc) be setup without PRs

### CODE REVIEW

**Comment by dragan** [comment]
PR's are fine. I went ahead and updated the board too.

**Comment by dragan** [comment]
@ncronquist Make sure you estimate the work.

**Review by nicklathe — APPROVED** [review]
:shipit:

**Review by dragan — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
